version: '3.7'

services: 

    arachni:

        build: .
        command: bash -c "sleep 10 && entrypoint.sh"
        environment:
          DB_ADAPTER: postgresql
          DB_HOST: postgres
          DB_NAME: arachni
          DB_USER: adminweb
          DB_PASS: webapp
        ports:
          - 7331:7331
          - 9292:9292
          - 22:22

        depends_on:
          - postgres
    
    postgres:

        image: postgres:9.6
        restart: always
        environment: 
            - POSTGRES_DB:'arachni'
            - POSTGRES_USER:'adminweb'
            - POSTGRES_PASSWORD:'webapp'
            - PGDATA:'/var/lib/postgresql/data/pgdata'
        volumes: 
            - $PWD/data/:/var/lib/postgresql/data/pgdata
        ports: 
            - 5432:5432